---
- name: Change password for user mfg
  hosts: all
  become: yes
  vars_files:
    - vars.yml  # Reference to the vars file
  tasks:
    - name: Change password for user mfg
      ansible.builtin.user:
        name: mfg
        password: "{{ newpassword_mfg | password_hash('sha512') }}"