---
- name: Change root password
  hosts: all
  become: yes
  vars_files:
   - vars.yml
  tasks:
    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ newpassword | password_hash('sha512') }}"
