- name: Start QADERP service using yab
  hosts: target_servers
  become: yes
  become_user: mfg
  tasks:
    - name: Run yab to start service
      shell: |
        cd /sw/apps/qaderp/
        alias yab="/sw/apps/qaderp/yab -a:/sw/apps/qaderp"
        yab -threads:10 start
      executable: /bin/bash
