---
- name: Install and Configure Nginx on RHEL 8
  hosts: all
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start Nginx service
      systemd:
        name: nginx
        state: started

    - name: Enable Nginx service at boot
      systemd:
        name: nginx
        enabled: yes
